"""empty message

Revision ID: 241b03e3fe9e
Revises: 757ea9b7a219
Create Date: 2019-09-23 18:00:11.378870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '241b03e3fe9e'
down_revision = '757ea9b7a219'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cms_role_user', sa.Column('cms_user_id', sa.Integer(), nullable=False))
    op.drop_constraint('cms_role_user_ibfk_1', 'cms_role_user', type_='foreignkey')
    op.create_foreign_key(None, 'cms_role_user', 'cms_user', ['cms_user_id'], ['id'])
    op.create_foreign_key(None, 'cms_role_user', 'cms_role', ['cms_role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cms_role_user', type_='foreignkey')
    op.drop_constraint(None, 'cms_role_user', type_='foreignkey')
    op.create_foreign_key('cms_role_user_ibfk_1', 'cms_role_user', 'cms_user', ['cms_role_id'], ['id'])
    op.drop_column('cms_role_user', 'cms_user_id')
    # ### end Alembic commands ###
