"""empty message

Revision ID: 92ab641c2eba
Revises: 6df082845f54
Create Date: 2019-09-21 21:52:00.266913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92ab641c2eba'
down_revision = '6df082845f54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cms_user', sa.Column('catptcha_code', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cms_user', 'catptcha_code')
    # ### end Alembic commands ###
