"""empty message

Revision ID: b1d3f7173050
Revises: 92ab641c2eba
Create Date: 2019-09-23 17:01:19.799820

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b1d3f7173050'
down_revision = '92ab641c2eba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cms_user', 'catptcha_code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cms_user', sa.Column('catptcha_code', mysql.VARCHAR(length=10), nullable=True))
    # ### end Alembic commands ###
